name: build

on:
  push:
    branches-ignore:
      - 'release*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - <<: *setup-java
      - name: Build with Maven
        run: mvn clean compile install -DskipTests --file pom.xml

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - <<: *setup-java
      - name: Run unit tests
        run: mvn test --file pom.xml

  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - <<: *setup-java
      - name: Maven Package
        run: mvn -B clean package -DskipTests

  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - <<: *setup-java
      - name: Maven Verify
        run: mvn -B clean verify

# Define the setup-java step as an anchor
setup-java: &setup-java
  name: Set up JDK 21
  uses: actions/setup-java@v3
  with:
    distribution: 'temurin'
    java-version: '21'
